// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC3r97NWTH0TbgfV1MFWm7RYVGB6Q9W5s',
    appId: '1:456222068260:android:4e55a8b7b97b5c19d112b1',
    messagingSenderId: '456222068260',
    projectId: 'shopsyapp-3a5b9',
    storageBucket: 'shopsyapp-3a5b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJo1nLLDx9OTcnVFvf7IGQZ2nTtc-XMRY',
    appId: '1:456222068260:ios:b37523aea98515a9d112b1',
    messagingSenderId: '456222068260',
    projectId: 'shopsyapp-3a5b9',
    storageBucket: 'shopsyapp-3a5b9.appspot.com',
    iosClientId: '456222068260-1jeqkqv8nms0vlmcuh9mr9m7cb0ll2t6.apps.googleusercontent.com',
    iosBundleId: 'com.dipak.shopsyApp',
  );
}
